@startuml
actor Actor as "actor"
participant MapaService as ":MapaService"
participant MapaRepositoryImp as ":MapaRepositoryImp"
participant MapaDAOJsonImpl as ":MapaDAOJsoImpl"
participant MapaDto as ":MapaDto"
participant MapaMapper as ":MapaMapper"
participant Mapa as ":Mapa"
participant CaminoRepositoryImpl as ":CaminoRepositoryImpl"

  activate Actor
    Actor->MapaService: cargarMapa()
    activate MapaService
      MapaService->CaminoRepositoryImpl: obtener()
      note over MapaDto: Para mas detalles de CaminoRepositoryImpl.obtener() mirar su diagrama especifico
      activate CaminoRepositoryImpl
      CaminoRepositoryImpl-->MapaService: camino:Camino
      deactivate CaminoRepositoryImpl
      MapaService->MapaRepositoryImp: obtener()
      activate MapaRepositoryImp
      MapaRepositoryImp->MapaDAOJsonImpl: obtener()
      activate MapaDAOJsonImpl
      MapaDAOJsonImpl->MapaDto: setAncho
      activate MapaDto
      MapaDto-->MapaDAOJsonImpl
      MapaDAOJsonImpl->MapaDto: setLargo
      MapaDto-->MapaDAOJsonImpl
      deactivate MapaDto
      MapaDAOJsonImpl-->MapaRepositoryImp: mapaDto: MapaDto
      deactivate MapaDAOJsonImpl
      MapaRepositoryImp->MapaMapper: convertirDesdeDto(mapaDto)
      activate MapaMapper
      MapaMapper->Mapa: << createRequest >>
      activate Mapa
      Mapa-->MapaMapper: RequestCreated
      MapaMapper-->MapaRepositoryImp: mapa
      deactivate MapaMapper
      MapaRepositoryImp-->MapaService: mapa
      deactivate MapaRepositoryImp
      MapaService->Mapa: setCamino(camino)
      Mapa-->MapaService: void
      deactivate Mapa
      MapaService-->Actor: mapa
    deactivate MapaService
  deactivate Actor
@enduml