@startuml
participant entrega_1 as "entrega_1"
participant consecuencias as "consecuencias"
participant Gladiador as "Gladiador"
participant Energia as "Energia"
participant observers as "observers"
  [->entrega_1: verificarQueSiRecibeComidaIncrementaEnergiaEn15 <color:gray> 16.9 ms</color>
  activate entrega_1
    entrega_1->consecuencias: afectarGladiador <color:gray> 14.5 ms</color>
    activate consecuencias
      consecuencias->Gladiador: comer <color:gray> 6.67 ms</color>
      activate Gladiador
        Gladiador->Energia: aumentarEnergia <color:gray> 0.699 ms</color>
        activate Energia
          Energia->observers: notificar <color:gray> 0.0271 ms</color>
          activate observers
          Energia<--observers: void
          deactivate observers
        Gladiador<--Energia: void
        deactivate Energia
      consecuencias<--Gladiador: void
      deactivate Gladiador
    entrega_1<--consecuencias: void
    deactivate consecuencias
  [<--entrega_1: void
  deactivate entrega_1
@enduml