@startuml
participant CasoDeUso19Test as "CasoDeUso19Test"
participant AlgoRoma as "AlgoRoma"
participant JuegoSinIniciar as "JuegoSinIniciar"
participant Gladiador as "Gladiador"
participant ObservableAlgoRoma as "ObservableAlgoRoma"
participant Mapa as "Mapa"
participant Camino as "Camino"
participant Energia as "Energia"
participant Senority as "Senority"
participant NovatoState as "NovatoState"
participant ObservableEnergia as "ObservableEnergia"
participant Celda as "Celda"
participant EquipamientoIncrementado as "EquipamientoIncrementado"
participant SinEquipamiento as "SinEquipamiento"
participant ObservableMapa as "ObservableMapa"

  activate CasoDeUso19Test
    CasoDeUso19Test->AlgoRoma: jugarTurno <color:gray> 0.381 ms</color>
    activate AlgoRoma
      AlgoRoma->JuegoSinIniciar: jugarTurno <color:gray> 0.369 ms</color>
      activate JuegoSinIniciar
        JuegoSinIniciar->AlgoRoma: jugarTurnoSegunEstado <color:gray> 0.351 ms</color>
        activate AlgoRoma
          AlgoRoma->Mapa: setGladiadores <color:gray> 0.0049 ms</color>
          activate Mapa
          AlgoRoma<--Mapa: void
          deactivate Mapa
          AlgoRoma->ObservableAlgoRoma: notificarNuevoTurno <color:gray> 0.0027 ms</color>
          activate ObservableAlgoRoma
          AlgoRoma<--ObservableAlgoRoma: void
          deactivate ObservableAlgoRoma
          AlgoRoma->Mapa: avanzarNPosicionesGladiador <color:gray> 0.274 ms</color>
          activate Mapa
            Mapa->Camino: proximoEnNPosiciones <color:gray> 0.0098 ms</color>
            activate Camino
            Mapa<--Camino: edu.fiuba.algo3.modelo.celda.Celda
            deactivate Camino
            Mapa->Gladiador: avanzar <color:gray> 0.0577 ms</color>
            activate Gladiador
              Gladiador->Energia: isAgotada <color:gray> 0.0037 ms</color>
              activate Energia
              Gladiador<--Energia: java.lang.Boolean
              deactivate Energia
              Gladiador->Senority: aumentarEnergia <color:gray> 0.0297 ms</color>
              activate Senority
                Senority->NovatoState: aumentarEnergia <color:gray> 0.0237 ms</color>
                activate NovatoState
                  NovatoState->Energia: aumentarEnergia <color:gray> 0.0147 ms</color>
                  activate Energia
                    Energia->ObservableEnergia: notificar <color:gray> 0.0062 ms</color>
                    activate ObservableEnergia
                    Energia<--ObservableEnergia: void
                    deactivate ObservableEnergia
                  NovatoState<--Energia: void
                  deactivate Energia
                Senority<--NovatoState: void
                deactivate NovatoState
              Gladiador<--Senority: void
              deactivate Senority
              Gladiador->Senority: aumentarExperiencia <color:gray> 0.0088 ms</color>
              activate Senority
                Senority->NovatoState: aumentarExperiencia <color:gray> 0.0033 ms</color>
                activate NovatoState
                Senority<--NovatoState: edu.fiuba.algo3.modelo.gladiador.senority.states.N
                deactivate NovatoState
              Gladiador<--Senority: void
              deactivate Senority
            Mapa<--Gladiador: void
            deactivate Gladiador
            Mapa->Celda: afectarGladiadorConConsecuencia <color:gray> 0.12 ms</color>
            activate Celda
              Celda->EquipamientoIncrementado: afectarGladiador <color:gray> 0.112 ms</color>
              activate EquipamientoIncrementado
                EquipamientoIncrementado->Gladiador: incrementarEquipamiento <color:gray> 0.0969 ms</color>
                activate Gladiador
                  Gladiador->SinEquipamiento: incrementar <color:gray> 0.0067 ms</color>
                  activate SinEquipamiento
                  Gladiador<--SinEquipamiento: edu.fiuba.algo3.modelo.equipamientos.Casco
                  deactivate SinEquipamiento
                  Gladiador->Gladiador: notificarObservadoresEquipamiento <color:gray> 0.0091 ms</color>
                  activate Gladiador
                  Gladiador<--Gladiador: void
                  deactivate Gladiador
                EquipamientoIncrementado<--Gladiador: void
                deactivate Gladiador
              Celda<--EquipamientoIncrementado: void
              deactivate EquipamientoIncrementado
            Mapa<--Celda: void
            deactivate Celda
            Mapa->ObservableMapa: notificarPosicionamientoDeGladiador <color:gray> 0.0022 ms</color>
            activate ObservableMapa
            Mapa<--ObservableMapa: void
            deactivate ObservableMapa
          AlgoRoma<--Mapa: void
          deactivate Mapa
        JuegoSinIniciar<--AlgoRoma: void
        deactivate AlgoRoma
        JuegoSinIniciar->AlgoRoma: setEstadoJuego <color:gray> 0.0021 ms</color>
        activate AlgoRoma
        JuegoSinIniciar<--AlgoRoma: void
        deactivate AlgoRoma
      AlgoRoma<--JuegoSinIniciar: void
      deactivate JuegoSinIniciar
    CasoDeUso19Test<--AlgoRoma: void
    deactivate AlgoRoma

  [<--CasoDeUso19Test: void
  deactivate CasoDeUso19Test
@enduml